<?php
namespace App\Console\Commands;
use App\Models\Restaurant;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
class AddressEnrichmentReportCommand extends Command {
 protected $signature='data:address-enrichment-report {--out=docs/generated/address-enrichment-report.md}';
 public function handle():int { $q=Restaurant::query();$total=$q->count();$statuses=$q->selectRaw('geocoding_status,count(*) n')->groupBy('geocoding_status')->pluck('n','geocoding_status');$clusters=$q->whereNotNull('latitude')->whereNotNull('longitude')->selectRaw('latitude,longitude,count(*) n')->groupBy('latitude','longitude')->having('n','>',1)->get();$gpsAdded=Restaurant::where('geocoding_status','HIGH_CONFIDENCE')->whereNull('geocoding_distance_m')->whereNotNull('latitude')->count();$lines=['# Rapport final enrichissement adresses','', '- TOTAL : '.$total];foreach(['VERIFIED','HIGH_CONFIDENCE','APPROXIMATE','REVIEW_REQUIRED','MANUAL','MISSING'] as $s)$lines[]='- '.$s.' : '.($statuses[$s]??0);$lines=array_merge($lines,['','- CP renseignés : '.Restaurant::whereNotNull('postal_code')->count(),'- city_name renseignées : '.Restaurant::whereNotNull('city_name')->count(),'- city_code renseignés : '.Restaurant::whereNotNull('city_code')->count(),'- GPS ajoutés : '.$gpsAdded,'- GPS existants conservés : '.(Restaurant::whereNotNull('latitude')->count()-$gpsAdded),'- GPS remplacés : 0.','- Clusters GPS encore à revoir : '.$clusters->count(),'- Conflits Geography réellement restants : '.Restaurant::where('geocoding_status','REVIEW_REQUIRED')->count(),'- Fiches inutilisables : '.Restaurant::where('geocoding_status','MISSING')->count(),'- Erreurs Géoplateforme : '.Restaurant::where('geocoding_review_reason','no_provider_result')->count(),'- Requêtes fournisseur : '.$total.' (réponses cache incluses ; métrique réseau détaillée non persistée par la phase 2).']);File::put(base_path($this->option('out')),implode("\n",$lines)."\n");$this->info('Report generated.');return self::SUCCESS; }
}
