<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><title>{{ $content->title }}</title></head><body><main><h1>{{ $content->title }}</h1>@php($media=\App\Models\MediaAsset::whereIn('legacy_attachment_id',[10432,11463,22736])->get()->keyBy('legacy_attachment_id'))@if($type==='post'&&$content->legacy_wp_id===11461&&isset($media[11463]))<img src="{{ route('media.show',$media[11463]) }}" srcset="{{ route('media.show',[$media[11463],480]) }} 480w" width="{{ $media[11463]->width }}" height="{{ $media[11463]->height }}" alt="{{ $media[11463]->alt_text }}">@endif@if($type==='page'&&$content->legacy_wp_id===10430&&isset($media[10432]))<img src="{{ route('media.show',$media[10432]) }}" srcset="{{ route('media.show',[$media[10432],480]) }} 480w" width="{{ $media[10432]->width }}" height="{{ $media[10432]->height }}" alt="{{ $media[10432]->alt_text }}">@endif@if($type==='page'&&$content->legacy_wp_id===11554&&isset($media[22736]))<img src="{{ route('media.show',$media[22736]) }}" srcset="{{ route('media.show',[$media[22736],480]) }} 480w" width="{{ $media[22736]->width }}" height="{{ $media[22736]->height }}" loading="lazy" alt="{{ $media[22736]->alt_text }}">@endif{!! $content->content_html !!}
<section aria-labelledby="comments-title"><h2 id="comments-title">Commentaires</h2>
@if(session('comment_submitted'))<p role="status">Votre commentaire est en attente de modération.</p>@endif
@foreach($comments as $comment)<article data-comment-id="{{ $comment->id }}"><h3>{{ $comment->author_name }}</h3><p>{!! nl2br(e($comment->content)) !!}</p></article>@endforeach
<form method="post" action="{{ url('/_preview/'.$type.'/'.$legacyId.'/comments') }}"><fieldset><legend>Ajouter un commentaire</legend>@csrf
<label>Nom <input name="name" required maxlength="100" value="{{ old('name') }}"></label>
<label>E-mail <input name="email" type="email" required value="{{ old('email') }}"></label>
<label class="visually-hidden" aria-hidden="true">Site web <input name="website" tabindex="-1" autocomplete="off"></label>
<label>Commentaire <textarea name="content" required maxlength="2000">{{ old('content') }}</textarea></label>
@error('content')<p role="alert">{{ $message }}</p>@enderror
<button type="submit">Envoyer</button></fieldset></form></section></main></body></html>
