<?php
namespace App\Services;

class EmailTemplateRegistry
{
    /** @return array<string, array{name:string,description:string,variables:array<int,string>,subject:string,body:string,cta_label:?string}> */
    public function all(): array
    {
        return [
            'email_verification' => $this->definition('Vérification e-mail', 'Confirme l’adresse d’un compte.', ['site_name','user_name','verification_url'], 'Confirmez votre adresse e-mail - {{ site_name }}', "Bonjour {{ user_name }},\n\nConfirmez votre adresse e-mail pour activer votre compte {{ site_name }}.\n\nCe lien est temporaire et ne doit pas être transféré.", 'Confirmer mon adresse e-mail'),
            'contribution_email_verification' => $this->definition('Vérification e-mail de contribution', 'Confirme l’adresse avant d’envoyer un avis ou commentaire en modération.', ['site_name','user_name','contribution_label','verification_url'], 'Confirmez votre adresse e-mail - {{ site_name }}', "Bonjour {{ user_name }},\n\nConfirmez votre adresse e-mail pour envoyer votre {{ contribution_label }} à la modération de {{ site_name }}.\n\nCe lien est temporaire et ne doit pas être transféré.", 'Confirmer mon adresse e-mail'),
            'password_reset' => $this->definition('Réinitialisation du mot de passe', 'Lien sécurisé de réinitialisation.', ['site_name','user_name','reset_url'], 'Réinitialisez votre mot de passe - {{ site_name }}', "Bonjour {{ user_name }},\n\nVous recevez cet e-mail car une réinitialisation de mot de passe a été demandée. Si vous n’êtes pas concerné, aucune action n’est requise.", 'Réinitialiser mon mot de passe'),
            'password_changed' => $this->definition('Mot de passe modifié', 'Confirmation de changement de mot de passe.', ['site_name','user_name'], 'Mot de passe modifié - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre mot de passe {{ site_name }} vient d’être modifié. Si vous n’êtes pas à l’origine de cette action, contactez la modération.", null),
            'claim_received' => $this->definition('Revendication reçue', 'Confirmation au demandeur.', ['site_name','user_name','restaurant_name','action_url'], 'Demande de revendication reçue - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre demande pour {{ restaurant_name }} est en attente de modération.", 'Voir ma demande'),
            'claim_approved' => $this->definition('Revendication acceptée', 'Confirmation au propriétaire.', ['site_name','user_name','restaurant_name','action_url'], 'Revendication acceptée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre revendication de {{ restaurant_name }} a été acceptée.", 'Gérer mon restaurant'),
            'claim_rejected' => $this->definition('Revendication refusée', 'Information au demandeur.', ['site_name','user_name','restaurant_name','claim_note'], 'Revendication refusée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre revendication de {{ restaurant_name }} a été refusée.\n\n{{ claim_note }}", null),
            'claim_email_verification' => $this->definition('Vérification e-mail de revendication', 'Confirme l’adresse avant modération.', ['site_name','user_name','restaurant_name','verification_url'], 'Confirmez votre adresse - {{ site_name }}', "Bonjour {{ user_name }},\n\nConfirmez votre adresse e-mail pour que notre équipe puisse examiner votre demande pour {{ restaurant_name }}.", 'Confirmer mon adresse'),
            'claim_activation' => $this->definition('Activation espace restaurateur', 'Permet de choisir le premier mot de passe après validation.', ['site_name','user_name','restaurant_name','activation_url'], 'Votre revendication a été validée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre revendication de {{ restaurant_name }} a été validée. Activez votre espace restaurateur en choisissant votre mot de passe.", 'Activer mon espace restaurateur'),
            'contact_admin' => $this->definition('Nouveau message de contact', 'Notification au destinataire unique.', ['site_name','contact_name','contact_email','contact_subject','contact_message'], 'Nouveau message de contact - {{ site_name }}', "Nom : {{ contact_name }}\nE-mail : {{ contact_email }}\nSujet : {{ contact_subject }}\n\n{{ contact_message }}", null),
            'contact_confirmation' => $this->definition('Accusé de réception Contact', 'Confirmation envoyée au visiteur.', ['site_name','contact_name','contact_subject'], 'Nous avons bien reçu votre message - {{ site_name }}', "Bonjour {{ contact_name }},\n\nNous avons bien reçu votre message concernant « {{ contact_subject }} ». Nous vous répondrons dès que possible.", null),
            'restaurant_submission_email_verification' => $this->definition('Vérification e-mail d’une proposition', 'Demande au déposant de confirmer son adresse avant la revue de l’équipe.', ['site_name','restaurant_name','verification_url'], 'Validez votre adresse e-mail - {{ site_name }}', "Bonjour,\n\nConfirmez votre adresse e-mail pour que notre équipe puisse examiner votre proposition pour « {{ restaurant_name }} ».\n\nCe lien est temporaire et ne doit pas être transféré.", 'Valider mon adresse e-mail'),
            'restaurant_submission_email_confirmed' => $this->definition('E-mail de proposition confirmé', 'Confirme la proposition et permet au déposant d’activer son espace.', ['site_name','restaurant_name','activation_url'], 'Votre adresse e-mail est confirmée - {{ site_name }}', "Bonjour,\n\nVotre adresse e-mail pour « {{ restaurant_name }} » est confirmée. Votre demande est maintenant en attente de vérification par l’équipe Top Halal.\n\nActivez votre espace pour pouvoir suivre et adapter cette fiche.", 'Activer mon espace'),
            'restaurant_submission_admin_review' => $this->definition('Proposition de restaurant à vérifier', 'Alerte le destinataire opérationnel après confirmation de l’e-mail du déposant.', ['site_name','restaurant_name','submitter_email','admin_url'], 'Restaurant à vérifier - {{ site_name }}', "Bonjour,\n\nLe déposant de « {{ restaurant_name }} » a confirmé son adresse e-mail. La proposition est prête à être vérifiée par l’équipe Top Halal.\n\nE-mail du déposant : {{ submitter_email }}", 'Ouvrir les propositions'),
            'restaurant_published' => $this->definition('Restaurant publié', 'Informe le contributeur que sa proposition est désormais visible.', ['site_name','restaurant_name','restaurant_url'], 'Votre restaurant est publié - {{ site_name }}', "Bonjour,\n\nBonne nouvelle : « {{ restaurant_name }} » est maintenant publié sur {{ site_name }}.", 'Voir le restaurant'),
            'restaurant_removal_request_received' => $this->definition('Demande de suppression reçue', 'Confirme au gestionnaire que sa demande doit être examinée.', ['site_name','user_name','restaurant_name'], 'Demande de suppression reçue - {{ site_name }}', "Bonjour {{ user_name }},\n\nNous avons bien reçu votre demande de suppression pour « {{ restaurant_name }} ».\n\nLe restaurant reste en ligne tant que l’équipe Top Halal n’a pas validé la demande. Nous allons l’examiner.", null),
            'restaurant_removal_request_approved' => $this->definition('Demande de suppression acceptée', 'Confirme le retrait non destructif de la fiche.', ['site_name','user_name','restaurant_name'], 'Demande de suppression acceptée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre demande de suppression pour « {{ restaurant_name }} » a été acceptée. Le restaurant a été retiré de la partie publique de {{ site_name }}.", null),
            'restaurant_removal_request_rejected' => $this->definition('Demande de suppression refusée', 'Informe le gestionnaire que la fiche reste inchangée.', ['site_name','user_name','restaurant_name','removal_note'], 'Demande de suppression refusée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre demande de suppression pour « {{ restaurant_name }} » n’a pas été acceptée. Le restaurant reste inchangé.\n\n{{ removal_note }}", null),
            'restaurant_removal_request_admin_review' => $this->definition('Demande de suppression à examiner', 'Alerte le destinataire opérationnel lorsqu’un gestionnaire demande le retrait d’une fiche.', ['site_name','restaurant_name','user_name','removal_reason','admin_url'], 'Demande de suppression à examiner - {{ site_name }}', "Bonjour,\n\n{{ user_name }} demande la suppression de « {{ restaurant_name }} ».\n\nMotif : {{ removal_reason }}", 'Ouvrir les demandes'),
        ];
    }
    public function get(string $key): array { return $this->all()[$key] ?? throw new \InvalidArgumentException('Type d’e-mail inconnu.'); }
    private function definition(string $name, string $description, array $variables, string $subject, string $body, ?string $cta): array { return compact('name','description','variables','subject','body') + ['cta_label' => $cta]; }
}
