<?php
namespace App\Services;

class EmailTemplateRegistry
{
    /** @return array<string, array{name:string,description:string,variables:array<int,string>,subject:string,body:string,cta_label:?string}> */
    public function all(): array
    {
        return [
            'email_verification' => $this->definition('Vérification e-mail', 'Confirme l’adresse d’un compte.', ['site_name','user_name','verification_url'], 'Confirmez votre adresse e-mail - {{ site_name }}', "Bonjour {{ user_name }},\n\nConfirmez votre adresse e-mail pour activer votre compte {{ site_name }}.\n\nCe lien est temporaire et ne doit pas être transféré.", 'Confirmer mon adresse e-mail'),
            'password_reset' => $this->definition('Réinitialisation du mot de passe', 'Lien sécurisé de réinitialisation.', ['site_name','user_name','reset_url'], 'Réinitialisez votre mot de passe - {{ site_name }}', "Bonjour {{ user_name }},\n\nVous recevez cet e-mail car une réinitialisation de mot de passe a été demandée. Si vous n’êtes pas concerné, aucune action n’est requise.", 'Réinitialiser mon mot de passe'),
            'password_changed' => $this->definition('Mot de passe modifié', 'Confirmation de changement de mot de passe.', ['site_name','user_name'], 'Mot de passe modifié - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre mot de passe {{ site_name }} vient d’être modifié. Si vous n’êtes pas à l’origine de cette action, contactez la modération.", null),
            'claim_received' => $this->definition('Revendication reçue', 'Confirmation au demandeur.', ['site_name','user_name','restaurant_name','action_url'], 'Demande de revendication reçue - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre demande pour {{ restaurant_name }} est en attente de modération.", 'Voir ma demande'),
            'claim_approved' => $this->definition('Revendication acceptée', 'Confirmation au propriétaire.', ['site_name','user_name','restaurant_name','action_url'], 'Revendication acceptée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre revendication de {{ restaurant_name }} a été acceptée.", 'Gérer mon restaurant'),
            'claim_rejected' => $this->definition('Revendication refusée', 'Information au demandeur.', ['site_name','user_name','restaurant_name','claim_note'], 'Revendication refusée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre revendication de {{ restaurant_name }} a été refusée.\n\n{{ claim_note }}", null),
            'claim_email_verification' => $this->definition('Vérification e-mail de revendication', 'Confirme l’adresse avant modération.', ['site_name','user_name','restaurant_name','verification_url'], 'Confirmez votre adresse - {{ site_name }}', "Bonjour {{ user_name }},\n\nConfirmez votre adresse e-mail pour que notre équipe puisse examiner votre demande pour {{ restaurant_name }}.", 'Confirmer mon adresse'),
            'claim_activation' => $this->definition('Activation espace restaurateur', 'Permet de choisir le premier mot de passe après validation.', ['site_name','user_name','restaurant_name','activation_url'], 'Votre revendication a été validée - {{ site_name }}', "Bonjour {{ user_name }},\n\nVotre revendication de {{ restaurant_name }} a été validée. Activez votre espace restaurateur en choisissant votre mot de passe.", 'Activer mon espace restaurateur'),
            'contact_admin' => $this->definition('Nouveau message de contact', 'Notification au destinataire unique.', ['site_name','contact_name','contact_email','contact_subject','contact_message'], 'Nouveau message de contact - {{ site_name }}', "Nom : {{ contact_name }}\nE-mail : {{ contact_email }}\nSujet : {{ contact_subject }}\n\n{{ contact_message }}", null),
            'contact_confirmation' => $this->definition('Accusé de réception Contact', 'Confirmation envoyée au visiteur.', ['site_name','contact_name','contact_subject'], 'Nous avons bien reçu votre message - {{ site_name }}', "Bonjour {{ contact_name }},\n\nNous avons bien reçu votre message concernant « {{ contact_subject }} ». Nous vous répondrons dès que possible.", null),
            'restaurant_submission_received' => $this->definition('Proposition de restaurant reçue', 'Confirme au contributeur que sa proposition est en attente de modération.', ['site_name','restaurant_name'], 'Votre proposition a bien été reçue - {{ site_name }}', "Bonjour,\n\nNous avons bien reçu votre proposition pour « {{ restaurant_name }} ». Notre équipe va la vérifier avant publication.", null),
            'restaurant_published' => $this->definition('Restaurant publié', 'Informe le contributeur que sa proposition est désormais visible.', ['site_name','restaurant_name','restaurant_url'], 'Votre restaurant est publié - {{ site_name }}', "Bonjour,\n\nBonne nouvelle : « {{ restaurant_name }} » est maintenant publié sur {{ site_name }}.", 'Voir le restaurant'),
        ];
    }
    public function get(string $key): array { return $this->all()[$key] ?? throw new \InvalidArgumentException('Type d’e-mail inconnu.'); }
    private function definition(string $name, string $description, array $variables, string $subject, string $body, ?string $cta): array { return compact('name','description','variables','subject','body') + ['cta_label' => $cta]; }
}
