@php($aggregate = $restaurant->approvedReviewAggregate())
@php($hero = $restaurant->media->first()?->asset)
@php($schema = array_filter(['@context'=>'https://schema.org','@type'=>'Restaurant','name'=>$restaurant->name,'address'=>$restaurant->address ? ['@type'=>'PostalAddress','streetAddress'=>$restaurant->address,'postalCode'=>$restaurant->postal_code,'addressLocality'=>$restaurant->city_name,'addressCountry'=>'FR'] : null,'telephone'=>$restaurant->phone,'aggregateRating'=>$aggregate['count'] ? ['@type'=>'AggregateRating','ratingValue'=>$aggregate['average'],'reviewCount'=>$aggregate['count'],'bestRating'=>5,'worstRating'=>1] : null]))
<x-layouts.app title="{{ $restaurant->name }} | Top Halal" canonical="{{ route('restaurants.show', $restaurant->slug) }}" robots="index,follow">
<x-slot:head><script type="application/ld+json">@json($schema)</script></x-slot:head>
<div class="shell"><nav class="breadcrumbs" aria-label="Fil d’Ariane"><a href="{{ route('home') }}">Accueil</a><span>/</span><a href="{{ route('restaurants.index') }}">Restaurants</a><span>/</span><span aria-current="page">{{ $restaurant->name }}</span></nav>
<article class="restaurant-detail"><div class="restaurant-main"><p class="eyebrow">Restaurant halal @if($restaurant->city_name) · {{ $restaurant->city_name }} @endif</p><h1>{{ $restaurant->name }}</h1>
@if($aggregate['count'])<p class="rating">★ {{ number_format($aggregate['average'],1,',','') }}/5 <a href="#avis">{{ $aggregate['count'] }} avis</a></p>@endif
@if($hero && $hero->width && $hero->height)<img class="restaurant-hero" src="{{ route('media.show', [$hero, 960]) }}" width="{{ $hero->width }}" height="{{ $hero->height }}" fetchpriority="high" alt="{{ $hero->alt_text ?: $restaurant->name }}">@endif
@if($restaurant->description)<section class="prose"><h2>À propos</h2><p>{{ $restaurant->description }}</p></section>@endif
@if($restaurant->categories->isNotEmpty() || $restaurant->features->isNotEmpty())<section><h2>Informations</h2><ul class="tags">@foreach($restaurant->categories as $category)<li>{{ $category->name }}</li>@endforeach @foreach($restaurant->features as $feature)<li>{{ $feature->name }}</li>@endforeach</ul></section>@endif
</div><aside class="contact-card"><h2>Coordonnées</h2>@if($restaurant->address)<p>{{ $restaurant->address }}@if($restaurant->postal_code || $restaurant->city_name)<br>{{ $restaurant->postal_code }} {{ $restaurant->city_name }}@endif</p>@endif @if($restaurant->phone)<a class="button" href="tel:{{ preg_replace('/[^+0-9]/', '', $restaurant->phone) }}">Appeler</a>@endif @auth<a class="button button-secondary" href="{{ route('claims.create', $restaurant) }}">Revendiquer cette adresse</a>@endauth</aside></article>
@if($restaurant->media->count() > 1)<section class="section"><h2>Galerie</h2><div class="gallery">@foreach($restaurant->media->skip(1) as $item)@if($asset = $item->asset)<img src="{{ route('media.show', [$asset, 480]) }}" width="{{ $asset->width }}" height="{{ $asset->height }}" loading="lazy" alt="{{ $asset->alt_text ?: $restaurant->name }}">@endif @endforeach</div></section>@endif
<section id="avis" class="section reviews"><h2>Avis</h2>@if(session('review_submitted'))<p class="flash" role="status">Merci, votre avis sera publié après modération.</p>@endif @forelse($reviews as $review)<article class="review"><p class="rating">{{ str_repeat('★', $review->rating) }}<span class="sr-only">{{ $review->rating }} sur 5</span></p><h3>{{ $review->title }}</h3><p>{{ $review->content }}</p><p class="muted">{{ $review->author_name }}</p></article>@empty <p>Aucun avis publié pour le moment.</p>@endforelse
<details><summary>Donner mon avis</summary><form class="stack-form" method="post" action="{{ route('restaurants.reviews.store', $restaurant->slug) }}">@csrf<label>Nom <input name="name" required value="{{ old('name') }}"></label><label>E-mail <input name="email" type="email" required value="{{ old('email') }}"></label><label>Note <select name="rating" required><option value="">Choisir</option>@for($i=5;$i>=1;$i--)<option value="{{ $i }}">{{ $i }}/5</option>@endfor</select></label><label>Titre (facultatif) <input name="title" value="{{ old('title') }}"></label><label>Avis <textarea name="content" required maxlength="3000">{{ old('content') }}</textarea></label><input class="hp" name="website" tabindex="-1" autocomplete="off"><button class="button">Envoyer pour modération</button></form></details></section></div>
</x-layouts.app>
