@php($isPreview = $preview ?? false)
@php($robots = $isPreview ? 'noindex,nofollow' : \App\Support\RobotsMeta::forRestaurant($restaurant))
@php($title = \App\Support\RestaurantSeo::title($restaurant))
@php($aggregate = $restaurant->approvedReviewAggregate())
@php($restaurantImages = $restaurant->media->filter(fn ($item) => $item->role !== 'fallback_thumbnail' && $item->asset?->isRestaurantImage())->values())
@php($hero = $restaurantImages->first()?->asset)
@php($heroVariant = $hero?->variants->where('width', '>=', 960)->sortBy('width')->first() ?? $hero?->variants->sortByDesc('width')->first())
@php($heroUrl = $hero ? $hero->deliveryUrl($heroVariant?->width) : null)
@php($hasStructuredAddress = filled($restaurant->address_line1) || filled($restaurant->postal_code) || filled($restaurant->city_name))
@php($displayAddress = $hasStructuredAddress ? $restaurant->address_line1 : preg_replace('/,?\s*France\s*$/iu', '', (string) $restaurant->address))
@php($openingHours = $restaurant->openingHours->groupBy('day'))
@php($days = ['monday' => 'Lundi', 'tuesday' => 'Mardi', 'wednesday' => 'Mercredi', 'thursday' => 'Jeudi', 'friday' => 'Vendredi', 'saturday' => 'Samedi', 'sunday' => 'Dimanche'])
@php($formatTime = fn ($time) => $time ? substr((string) $time, 0, 5) : null)
@php($openingHoursStatus = app(\App\Services\RestaurantOpeningStatus::class)->for($restaurant->openingHours))
@php($outboundLinks = $isPreview ? collect() : app(\App\Services\RestaurantOutboundLinks::class)->publicLinks($restaurant->outboundLinks))
@php($schemaAddress = $hasStructuredAddress ? array_filter(['@type'=>'PostalAddress','streetAddress'=>$restaurant->address_line1,'postalCode'=>$restaurant->postal_code,'addressLocality'=>$restaurant->city_name,'addressCountry'=>$restaurant->country_code ?: 'FR']) : ($restaurant->address ? ['@type'=>'PostalAddress','streetAddress'=>$restaurant->address] : null))
@php($schema = array_filter(['@context'=>'https://schema.org','@type'=>'Restaurant','name'=>$restaurant->name,'address'=>$schemaAddress,'telephone'=>$restaurant->phone,'aggregateRating'=>$aggregate['count'] ? ['@type'=>'AggregateRating','ratingValue'=>$aggregate['average'],'reviewCount'=>$aggregate['count'],'bestRating'=>5,'worstRating'=>1] : null]))
@php($breadcrumbItems = $breadcrumbs ?? [['label' => 'Accueil', 'url' => route('home')], ['label' => 'Restaurants', 'url' => route('restaurants.index')], ['label' => $restaurant->name, 'url' => null]])
<x-layouts.app :title="$title" :canonical="$isPreview ? ($previewUrl ?? route('restaurants.preview', $restaurant->legacy_wp_id)) : route('restaurants.show', $restaurant->slug)" :robots="$robots" :admin-edit-url="$adminEditUrl ?? null" :hide-flash="$errors->hasAny(['name', 'email', 'rating', 'content', 'website'])">
<x-slot:head><script type="application/ld+json">@json($schema)</script></x-slot:head>
<div class="shell"><x-breadcrumbs :items="$breadcrumbItems" />
@php($restaurantH1 = \Illuminate\Support\Str::startsWith(\Illuminate\Support\Str::lower($restaurant->name), 'quick halal') ? $restaurant->name : (\Illuminate\Support\Str::startsWith(\Illuminate\Support\Str::lower($restaurant->name), 'quick ') ? 'Quick Halal '.preg_replace('/^quick\s+/i', '', $restaurant->name) : $restaurant->name))
<article class="restaurant-detail"><div class="restaurant-main"><p class="eyebrow">Restaurant halal @if($restaurant->city_name) · {{ $restaurant->city_name }} @endif</p><h1>{{ $restaurantH1 }}</h1>
@if($aggregate['count'])<p class="rating">★ {{ number_format($aggregate['average'],1,',','') }}/5 <a href="#avis">{{ $aggregate['count'] }} avis</a></p>@endif
@if($hero && $hero->width && $hero->height)<img class="restaurant-hero" src="{{ $heroUrl }}" width="{{ $hero->width }}" height="{{ $hero->height }}" fetchpriority="high" alt="{{ $hero->alt_text ?: $restaurant->name }}">@endif
@if($restaurant->description)<section class="prose"><h2>À propos</h2><p>{{ $restaurant->description }}</p></section>@endif
@if($restaurant->openingHours->isNotEmpty())<section class="opening-hours" aria-labelledby="horaires"><h2 id="horaires">Horaires</h2><div class="opening-hours-card">@if($openingHoursStatus['message'])<p class="opening-hours-status">{{ $openingHoursStatus['message'] }}</p>@endif<dl class="opening-hours-list">@foreach($days as $day => $label)@php($slots = $openingHours->get($day, collect()))@php($displaySlots = $slots->reject('is_closed')->filter(fn ($slot) => $formatTime($slot->opens_at) && $formatTime($slot->closes_at)))@if($slots->isNotEmpty())<div @if($openingHoursStatus['day'] === $day) class="is-today" aria-current="date" @endif><dt>{{ $label }}@if($openingHoursStatus['day'] === $day)<span class="sr-only"> (aujourd’hui)</span>@endif</dt><dd>@if($slots->every('is_closed'))Fermé@elseif($displaySlots->isNotEmpty()){{ $displaySlots->map(fn ($slot) => $slot->is_open_24_hours ? 'Ouvert 24h/24' : $formatTime($slot->opens_at).'–'.$formatTime($slot->closes_at))->implode(' · ') }}@endif</dd></div>@endif@endforeach</dl></div></section>@endif
@if($restaurant->categories->isNotEmpty() || $restaurant->features->isNotEmpty())<section class="restaurant-information"><h2>Informations</h2>@if($restaurant->categories->isNotEmpty())<h3>Spécialités</h3><ul class="tags">@foreach($restaurant->categories as $category)<li>{{ $category->name }}</li>@endforeach</ul>@endif @if($restaurant->features->isNotEmpty())<h3>Services</h3><ul class="service-list">@foreach($restaurant->features as $feature)<li><x-service-icon :name="$feature->name" /> <span>{{ $feature->name }}</span></li>@endforeach</ul>@endif</section>@endif
</div><aside class="contact-card"><h2>Coordonnées</h2>@if($displayAddress)<p>{{ $displayAddress }}@if($restaurant->postal_code || $restaurant->city_name)<br>{{ $restaurant->postal_code }} {{ $restaurant->city_name }}@endif</p>@endif @if($restaurant->phone)<a class="button" href="tel:{{ preg_replace('/[^+0-9]/', '', $restaurant->phone) }}">Appeler</a>@endif @if($outboundLinks->isNotEmpty())<nav class="restaurant-outbound-actions" aria-label="Liens externes du restaurant">@foreach($outboundLinks as $link)<form method="post" action="{{ route('restaurants.outbound') }}" target="_blank" rel="noopener">@csrf<input type="hidden" name="token" value="{{ $link->token }}"><button class="button button-secondary" type="submit"><x-restaurant-outbound-icon :label="$link->label" /> <span>{{ $link->label }}</span></button></form>@endforeach</nav>@endif @if(! $isPreview && $restaurant->isClaimable()) <a class="button button-secondary" href="{{ route('claims.create', $restaurant) }}">Revendiquer ce restaurant</a> @endif</aside></article>
@if($restaurantImages->count() > 1)<section class="section"><h2>Galerie</h2><div class="gallery">@foreach($restaurantImages->skip(1) as $item)@php($asset = $item->asset)@php($galleryVariant = $asset->variants->where('width', '>=', 480)->sortBy('width')->first() ?? $asset->variants->sortByDesc('width')->first())<img src="{{ $asset->deliveryUrl($galleryVariant?->width) }}" width="{{ $asset->width }}" height="{{ $asset->height }}" loading="lazy" alt="{{ $asset->alt_text ?: $restaurant->name }}">@endforeach</div></section>@endif
<section id="avis" class="section reviews"><h2>Avis</h2><p data-review-aggregate>{{ $aggregate['count'] }} avis{{ $aggregate['average'] !== null ? ', moyenne '.number_format($aggregate['average'], 2, ',', '').'/5' : '' }}</p>@if(session('review_submitted'))<p class="flash" role="status">Merci, votre avis sera publié après modération.</p>@elseif(session('contribution_verification_sent'))<p class="flash" role="status">Vérifiez votre adresse e-mail pour confirmer votre avis.</p>@endif @forelse($reviews as $review)<article class="review"><p class="rating">{{ str_repeat('★', $review->rating) }}<span class="sr-only">{{ $review->rating }} sur 5</span></p>@if(filled($review->title))<h3>{{ $review->title }}</h3>@endif<p>{{ $review->content }}</p><p class="muted">{{ $review->author_name }} · <time datetime="{{ $review->created_at->toDateString() }}">Publié le {{ $review->created_at->translatedFormat('j F Y') }}</time></p></article>@empty <div class="reviews-empty-state"><p>Aucun avis pour le moment.</p><p>Vous connaissez {{ $restaurant->name }} ?<br>Partagez votre expérience avec la communauté Top Halal.</p></div>@endforelse
@if(! $isPreview)@if(auth()->user()?->can('isRestaurantManager', $restaurant))<p class="flash" role="status">{{ \App\Exceptions\RestaurantReviewOwnershipException::MESSAGE }}</p>@else<details class="review-form-disclosure" @if($errors->hasAny(['name', 'email', 'rating', 'content', 'website'])) open @endif><summary>Donner mon avis</summary><form class="review-form" method="post" action="{{ route('restaurants.reviews.store', $restaurant->slug) }}">@csrf<div class="review-identity-fields"><label for="review-name">Prénom ou pseudo <input id="review-name" name="name" required maxlength="100" value="{{ old('name', auth()->user()?->name) }}" @error('name') aria-describedby="review-name-error" aria-invalid="true" @enderror></label>@guest<label for="review-email">E-mail <input id="review-email" name="email" type="email" required maxlength="255" value="{{ old('email') }}" @error('email') aria-describedby="review-email-error" aria-invalid="true" @enderror></label>@endguest</div>@error('name')<p id="review-name-error" class="field-error" role="alert">{{ $message }}</p>@enderror @guest@error('email')<p id="review-email-error" class="field-error" role="alert">{{ $message }}</p>@enderror@endguest<fieldset class="review-rating-fieldset" @error('rating') aria-describedby="review-rating-error" @enderror><legend>Votre note</legend><div class="review-rating-options">@for($i = 1; $i <= 5; $i++)<input class="review-rating-input" id="review-rating-{{ $i }}" type="radio" name="rating" value="{{ $i }}" required @checked((string) old('rating') === (string) $i)><label class="review-rating-star" for="review-rating-{{ $i }}"><span aria-hidden="true">★</span><span class="sr-only">{{ $i }} {{ $i === 1 ? 'étoile' : 'étoiles' }}</span></label>@endfor<p class="review-rating-hint" aria-live="polite"><span class="rating-prompt">Choisissez une note</span><span class="rating-value-1">Décevant</span><span class="rating-value-2">Moyen</span><span class="rating-value-3">Bien</span><span class="rating-value-4">Très bien</span><span class="rating-value-5">Excellent</span></p></div></fieldset>@error('rating')<p id="review-rating-error" class="field-error" role="alert">{{ $message }}</p>@enderror<label for="review-content">Votre avis <textarea id="review-content" name="content" required maxlength="3000" @error('content') aria-describedby="review-content-error" aria-invalid="true" @enderror>{{ old('content') }}</textarea></label>@error('content')<p id="review-content-error" class="field-error" role="alert">{{ $message }}</p>@enderror<input class="hp" name="website" tabindex="-1" autocomplete="off"><p class="form-help">Votre e-mail ne sera jamais affiché publiquement. Il sert uniquement à confirmer votre avis.</p><div class="review-form-actions"><button class="button">Envoyer mon avis</button></div></form></details>@endif@endif</section>
@if(! $isPreview)
<section class="section report-correction"><h2>Une information à corriger ?</h2>
@if(session('content_report_submitted'))
<p class="flash" role="status">Merci, votre signalement a été transmis à Top Halal.</p>
@elseif(session('content_report_verification_sent'))
<p class="flash" role="status">Vérifiez votre adresse e-mail pour transmettre votre signalement.</p>
@else
@if(auth()->user() && app(\App\Policies\RestaurantPolicy::class)->manage(auth()->user(), $restaurant))
<p>Vous pouvez modifier cette fiche directement.</p><a class="button" href="{{ route('owner.restaurants.edit', $restaurant) }}">Modifier les informations de cette fiche</a><p class="muted">Pour tout autre problème, vous pouvez aussi nous le signaler ci-dessous.</p>
@endif
<details><summary>Signaler une erreur</summary><form class="stack-form" method="post" action="{{ route('restaurants.reports.store', $restaurant->slug) }}">@csrf
@if(auth()->check())
<p class="muted">Signalement envoyé avec le compte {{ auth()->user()->email }}.</p>
@else
<label for="report-email">E-mail <input id="report-email" name="email" type="email" required value="{{ old('email') }}"></label>
@endif
<label for="report-message">Information à corriger <textarea id="report-message" name="message" maxlength="2000" required>{{ old('message') }}</textarea></label><input class="hp" name="website" tabindex="-1" autocomplete="off"><button class="button">Envoyer le signalement</button></form></details>
@endif
</section>
@endif
</div>
</x-layouts.app>
