<?php
namespace Tests\Feature;
use App\Models\{Restaurant,RestaurantClaim,RestaurantSubmission,User}; use App\Services\ClaimModeration; use Illuminate\Foundation\Testing\DatabaseMigrations; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Notification; use Tests\TestCase;
class AuthenticationAndClaimsTest extends TestCase { use DatabaseMigrations;
 public function test_guest_sees_login_and_first_claim_cards():void{$this->get(route('claims.create',$this->restaurant()))->assertOk()->assertSee('Vous avez déjà un compte restaurateur ?')->assertSee('Première revendication ?')->assertSee('Se connecter et continuer');}
 public function test_generic_registration_is_removed_while_the_legacy_claim_hand_off_returns_to_the_claim_form():void{$restaurant=$this->restaurant();$this->get('/register')->assertNotFound();$this->post('/register')->assertMethodNotAllowed();$this->get(route('claims.register',$restaurant))->assertRedirect(route('claims.create',$restaurant));}
 public function test_login_and_password_reset_use_the_shared_form_card_design():void{$this->get(route('login'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Content de vous revoir.');$this->get(route('password.request'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Retrouvez votre espace.');}
 public function test_password_change_uses_the_shared_form_card_design():void{$user=User::factory()->create();$this->actingAs($user)->get(route('password.change'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Choisissez votre mot de passe.');}
 public function test_restaurateur_can_log_out_from_the_account_dashboard():void{$user=User::factory()->create(['role'=>'user','must_change_password'=>false]);$this->actingAs($user)->get(route('account.dashboard'))->assertOk()->assertSee('Déconnexion');$this->actingAs($user)->post(route('logout'))->assertRedirect(route('home'));$this->assertGuest();}
 public function test_reset_and_verification_use_the_shared_form_card_design():void{$this->get(route('password.reset','token-test'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Protégez votre espace.');$user=User::factory()->create();$this->actingAs($user)->get(route('verification.notice'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Vérifiez votre e-mail.');}
 public function test_first_claim_requires_identity_and_email_confirmation_before_review():void{Notification::fake();$r=$this->restaurant();$this->post(route('claims.store',$r),['full_name'=>'Amina Martin','email'=>'amina@example.test','company'=>'SARL Test','siret'=>'73282932000074','certified'=>'1','identity_document'=>UploadedFile::fake()->image('identity.jpg',800,600)])->assertRedirect(route('claims.received'));$c=RestaurantClaim::firstOrFail();$this->assertSame('pending_email_verification',$c->status);$this->assertNull($c->user_id);$this->assertNotNull($c->identity_document_path);}
 public function test_authenticated_non_manager_depositor_sees_only_the_first_claim_dossier_for_its_own_claimable_restaurant():void{$restaurant=$this->restaurant();$depositor=User::factory()->create(['name'=>'Amina Martin','email'=>'amina@example.test']);RestaurantSubmission::create(['restaurant_id'=>$restaurant->id,'user_id'=>$depositor->id,'submitter_email'=>$depositor->email,'submitter_role'=>'customer','status'=>'published','submitted_at'=>now()]);$this->assertTrue($restaurant->isClaimable());$this->actingAs($depositor)->get(route('claims.create',$restaurant))->assertOk()->assertSee('Vérifiez votre identité')->assertSee('Vous êtes connecté en tant que Amina Martin — amina@example.test')->assertSee('value="Amina Martin"',false)->assertSee('readonly',false)->assertDontSee('Vous avez déjà un compte restaurateur ?')->assertDontSee('Se connecter et continuer');}
 public function test_restaurant_name_fallback_is_never_presented_as_a_depositor_personal_name():void{$restaurant=Restaurant::create(['name'=>'Restaurant Test','slug'=>'restaurant-test-'.str()->random(8),'status'=>'published']);$depositor=User::factory()->create(['name'=>'Restaurant Test','email'=>'user@example.fr']);RestaurantSubmission::create(['restaurant_id'=>$restaurant->id,'user_id'=>$depositor->id,'submitter_email'=>$depositor->email,'submitter_role'=>'customer','status'=>'published','submitted_at'=>now()]);$this->actingAs($depositor)->get(route('claims.create',$restaurant))->assertOk()->assertSee('Vérifiez votre identité')->assertSee('Vous êtes connecté avec l’adresse user@example.fr')->assertSee('value=""',false)->assertDontSee('Vous êtes connecté en tant que Restaurant Test')->assertDontSee('value="Restaurant Test"',false);}
 public function test_authenticated_first_claim_records_an_explicit_personal_name_on_a_depositor_without_one():void{Notification::fake();$restaurant=Restaurant::create(['name'=>'Restaurant Test','slug'=>'restaurant-test-'.str()->random(8),'status'=>'published']);$depositor=User::factory()->create(['name'=>'Restaurant Test','email'=>'user@example.fr']);RestaurantSubmission::create(['restaurant_id'=>$restaurant->id,'user_id'=>$depositor->id,'submitter_email'=>$depositor->email,'submitter_role'=>'customer','status'=>'published','submitted_at'=>now()]);$this->actingAs($depositor)->post(route('claims.store',$restaurant),['full_name'=>'Jean Dupont','company'=>'SARL Test','siret'=>'73282932000074','certified'=>'1','identity_document'=>UploadedFile::fake()->image('identity.jpg',800,600)]);$claim=RestaurantClaim::firstOrFail();$this->assertSame($depositor->id,$claim->user_id);$this->assertSame('Jean Dupont',$claim->full_name);$this->assertSame('Jean Dupont',$depositor->fresh()->name);$this->assertDatabaseCount('users',1);}
 public function test_authenticated_first_claim_uses_the_session_user_even_when_email_or_user_id_are_forged():void{Notification::fake();$restaurant=$this->restaurant();$depositor=User::factory()->create(['name'=>'Amina Martin','email'=>'amina@example.test']);$other=User::factory()->create(['email'=>'other@example.test']);RestaurantSubmission::create(['restaurant_id'=>$restaurant->id,'user_id'=>$depositor->id,'submitter_email'=>$depositor->email,'submitter_role'=>'customer','status'=>'published','submitted_at'=>now()]);$usersBefore=User::count();$this->actingAs($depositor)->post(route('claims.store',$restaurant),['full_name'=>'Amina Martin','email'=>$other->email,'user_id'=>$other->id,'company'=>'SARL Test','siret'=>'73282932000074','certified'=>'1','identity_document'=>UploadedFile::fake()->image('identity.jpg',800,600)])->assertRedirect();$claim=RestaurantClaim::firstOrFail();$this->assertSame($depositor->id,$claim->user_id);$this->assertSame($depositor->email,$claim->email);$this->assertSame('pending',$claim->status);$this->assertSame($usersBefore,User::count());$this->assertNull($claim->activation_token);}
 public function test_approval_of_an_authenticated_depositor_first_claim_reuses_the_active_account_without_activation():void{Notification::fake();$restaurant=$this->restaurant();$depositor=User::factory()->create(['name'=>'Amina Martin','email'=>'amina@example.test']);RestaurantSubmission::create(['restaurant_id'=>$restaurant->id,'user_id'=>$depositor->id,'submitter_email'=>$depositor->email,'submitter_role'=>'customer','status'=>'published','submitted_at'=>now()]);$this->actingAs($depositor)->post(route('claims.store',$restaurant),['full_name'=>'Amina Martin','company'=>'SARL Test','siret'=>'73282932000074','certified'=>'1','identity_document'=>UploadedFile::fake()->image('identity.jpg',800,600)]);$claim=RestaurantClaim::firstOrFail();$admin=User::factory()->create(['role'=>'admin']);$this->actingAs($admin);app(ClaimModeration::class)->approve($claim);$claim->refresh();$this->assertSame('approved',$claim->status);$this->assertSame($depositor->id,$claim->user_id);$this->assertNull($claim->activation_token);$this->assertTrue($depositor->fresh()->isVerifiedRestaurateur());$this->assertDatabaseCount('users',2);}
 public function test_verified_restaurateur_sees_and_submits_only_the_light_claim():void{Notification::fake();$r=$this->restaurant();$u=User::factory()->create(['role'=>'user','must_change_password'=>false]);RestaurantClaim::create(['restaurant_id'=>$this->restaurant()->id,'user_id'=>$u->id,'status'=>'approved','submitted_at'=>now()]);$this->actingAs($u)->get(route('claims.create',$r))->assertOk()->assertSee('Envoyer la demande')->assertDontSee('Photo de votre pièce d’identité')->assertDontSee('SIRET');$this->actingAs($u)->post(route('claims.store',$r),['certified'=>'1'])->assertRedirect();$c=RestaurantClaim::where('restaurant_id',$r->id)->firstOrFail();$this->assertSame('pending',$c->status);$this->assertSame($u->id,$c->user_id);}
 public function test_verified_email_cannot_open_a_second_identity_file():void{$user=User::factory()->create(['email'=>'owner@example.test','role'=>'user','must_change_password'=>false]);RestaurantClaim::create(['restaurant_id'=>$this->restaurant()->id,'user_id'=>$user->id,'status'=>'approved','submitted_at'=>now()]);$r=$this->restaurant();$this->from(route('claims.create',$r))->post(route('claims.store',$r),['full_name'=>'Amina Martin','email'=>'owner@example.test','company'=>'SARL Test','siret'=>'73282932000074','certified'=>'1','identity_document'=>UploadedFile::fake()->image('identity.jpg',800,600)])->assertSessionHasErrors('email');$this->assertDatabaseCount('restaurant_claims',1);}
 public function test_admin_approval_creates_activation_only_after_email_verification():void{Notification::fake();$r=$this->restaurant();$c=RestaurantClaim::create(['restaurant_id'=>$r->id,'full_name'=>'Amina Martin','email'=>'amina@example.test','company'=>'SARL Test','siret'=>'73282932000074','certified'=>true,'source'=>'first_claim','status'=>'pending','email_verified_at'=>now(),'submitted_at'=>now()]);$this->actingAs(User::factory()->create(['role'=>'admin']));app(ClaimModeration::class)->approve($c);$c->refresh();$this->assertSame('approved',$c->status);$this->assertNotNull($c->user_id);$this->assertNotNull($c->activation_token);$this->assertSame('user',$c->user->role);}
 public function test_unclaimable_restaurant_rejects_direct_post():void{$r=$this->restaurant();RestaurantClaim::create(['restaurant_id'=>$r->id,'user_id'=>User::factory()->create()->id,'status'=>'pending','submitted_at'=>now()]);$this->post(route('claims.store',$r),[])->assertSessionHasErrors('claim');}
 private function restaurant():Restaurant{return Restaurant::create(['legacy_wp_id'=>random_int(1,999999),'name'=>'L’Étoile','slug'=>'l-etoile-'.str()->random(8),'status'=>'published']);}}
