<?php
namespace Tests\Feature;
use App\Models\{Restaurant,RestaurantClaim,User}; use App\Services\ClaimModeration; use Illuminate\Foundation\Testing\DatabaseMigrations; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Notification; use Tests\TestCase;
class AuthenticationAndClaimsTest extends TestCase { use DatabaseMigrations;
 public function test_guest_sees_login_and_first_claim_cards():void{$this->get(route('claims.create',$this->restaurant()))->assertOk()->assertSee('Vous avez déjà un compte restaurateur ?')->assertSee('Première revendication ?')->assertSee('Se connecter et continuer');}
 public function test_generic_registration_is_removed_while_the_legacy_claim_hand_off_returns_to_the_claim_form():void{$restaurant=$this->restaurant();$this->get('/register')->assertNotFound();$this->post('/register')->assertMethodNotAllowed();$this->get(route('claims.register',$restaurant))->assertRedirect(route('claims.create',$restaurant));}
 public function test_login_and_password_reset_use_the_shared_form_card_design():void{$this->get(route('login'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Content de vous revoir.');$this->get(route('password.request'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Retrouvez votre espace.');}
 public function test_password_change_uses_the_shared_form_card_design():void{$user=User::factory()->create();$this->actingAs($user)->get(route('password.change'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Choisissez votre mot de passe.');}
 public function test_reset_and_verification_use_the_shared_form_card_design():void{$this->get(route('password.reset','token-test'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Protégez votre espace.');$user=User::factory()->create();$this->actingAs($user)->get(route('verification.notice'))->assertOk()->assertSee('contact-page auth-page',false)->assertSee('Vérifiez votre e-mail.');}
 public function test_first_claim_requires_identity_and_email_confirmation_before_review():void{Notification::fake();$r=$this->restaurant();$this->post(route('claims.store',$r),['full_name'=>'Amina Martin','email'=>'amina@example.test','company'=>'SARL Test','siret'=>'73282932000074','certified'=>'1','identity_document'=>UploadedFile::fake()->image('identity.jpg',800,600)])->assertRedirect(route('claims.received'));$c=RestaurantClaim::firstOrFail();$this->assertSame('pending_email_verification',$c->status);$this->assertNull($c->user_id);$this->assertNotNull($c->identity_document_path);}
 public function test_verified_restaurateur_sees_and_submits_only_the_light_claim():void{Notification::fake();$r=$this->restaurant();$u=User::factory()->create(['role'=>'restaurant_owner','must_change_password'=>false]);$this->actingAs($u)->get(route('claims.create',$r))->assertOk()->assertSee('Envoyer la demande')->assertDontSee('Photo de votre pièce d’identité')->assertDontSee('SIRET');$this->actingAs($u)->post(route('claims.store',$r),['certified'=>'1'])->assertRedirect();$c=RestaurantClaim::firstOrFail();$this->assertSame('pending',$c->status);$this->assertSame($u->id,$c->user_id);}
 public function test_verified_email_cannot_open_a_second_identity_file():void{User::factory()->create(['email'=>'owner@example.test','role'=>'restaurant_owner','must_change_password'=>false]);$r=$this->restaurant();$this->from(route('claims.create',$r))->post(route('claims.store',$r),['full_name'=>'Amina Martin','email'=>'owner@example.test','company'=>'SARL Test','siret'=>'73282932000074','certified'=>'1','identity_document'=>UploadedFile::fake()->image('identity.jpg',800,600)])->assertSessionHasErrors('email');$this->assertDatabaseCount('restaurant_claims',0);}
 public function test_admin_approval_creates_activation_only_after_email_verification():void{Notification::fake();$r=$this->restaurant();$c=RestaurantClaim::create(['restaurant_id'=>$r->id,'full_name'=>'Amina Martin','email'=>'amina@example.test','company'=>'SARL Test','siret'=>'73282932000074','certified'=>true,'source'=>'first_claim','status'=>'pending','email_verified_at'=>now(),'submitted_at'=>now()]);$this->actingAs(User::factory()->create(['role'=>'admin']));app(ClaimModeration::class)->approve($c);$c->refresh();$this->assertSame('approved',$c->status);$this->assertNotNull($c->user_id);$this->assertNotNull($c->activation_token);$this->assertSame('restaurant_owner',$c->user->role);}
 public function test_unclaimable_restaurant_rejects_direct_post():void{$r=$this->restaurant();RestaurantClaim::create(['restaurant_id'=>$r->id,'user_id'=>User::factory()->create()->id,'status'=>'pending','submitted_at'=>now()]);$this->post(route('claims.store',$r),[])->assertSessionHasErrors('claim');}
 private function restaurant():Restaurant{return Restaurant::create(['legacy_wp_id'=>random_int(1,999999),'name'=>'L’Étoile','slug'=>'l-etoile-'.str()->random(8),'status'=>'published']);}}
