<?php
namespace Tests\Feature;
use App\Models\{Article,ContentMedia,MediaAsset,RegressionDeploymentSnapshot,Restaurant}; use App\Services\Regression\SentinelRegistry; use Illuminate\Foundation\Testing\DatabaseMigrations; use Illuminate\Support\Facades\Storage; use Tests\TestCase;
class RegressionSentinelTest extends TestCase { use DatabaseMigrations;
 private function data():array{Storage::fake('local');$r=Restaurant::create(['legacy_wp_id'=>1,'name'=>'Fixture','slug'=>'fixture','status'=>'published']);$a=Article::create(['legacy_wp_id'=>2,'original_title'=>'A','title'=>'A','slug'=>'a','legacy_url'=>'/a','status'=>'published']);Storage::disk('local')->put('media/originals/a.jpg','x');$m=MediaAsset::create(['original_path'=>'media/originals/a.jpg','mime'=>'image/jpeg','bytes'=>1,'checksum'=>str_repeat('a',64),'status'=>'ready']);ContentMedia::create(['content_type'=>'post','content_id'=>$a->id,'media_asset_id'=>$m->id,'legacy_attachment_id'=>1,'role'=>'featured']);return[$r,$a,$m];}
 public function test_trashed_business_content_is_not_a_permanent_gate_fixture():void{[$r,$a]=$this->data();$a->delete();self::assertSame([],app(SentinelRegistry::class)->verify()['errors']);}
 public function test_referenced_missing_media_is_detected():void{[,, $m]=$this->data();Storage::disk('local')->delete($m->original_path);self::assertContains("Referenced media asset #{$m->id} source file is missing.",app(SentinelRegistry::class)->verify()['errors']);}
 public function test_orphaned_editorial_media_is_detected():void{[,$a,$m]=$this->data();$a->forceDelete();self::assertContains('Editorial media relation references a missing article.',app(SentinelRegistry::class)->verify()['errors']);}
 public function test_deployment_snapshot_detects_only_changes_after_capture():void{[$r]=$this->data();$s=RegressionDeploymentSnapshot::create(['run_id'=>'11111111-1111-4111-8111-111111111111','counts'=>app(SentinelRegistry::class)->counts(),'captured_at'=>now()]);$r->forceDelete();self::assertContains('Unexpected count decrease during this deployment for restaurants: 0 < 1.',app(SentinelRegistry::class)->verify($s->run_id)['errors']);}
 public function test_existing_business_count_changes_before_snapshot_do_not_fail():void{[$r]=$this->data();$r->delete();$s=RegressionDeploymentSnapshot::create(['run_id'=>'22222222-2222-4222-8222-222222222222','counts'=>app(SentinelRegistry::class)->counts(),'captured_at'=>now()]);self::assertSame([],app(SentinelRegistry::class)->verify($s->run_id)['errors']);}
}
