<?php

return [
    // A single published page is retained when a commune and its department
    // are the same administrative territory, rather than merely homonymous.
    'city_department_equivalences' => [
        '75056' => '75',
    ],

    'regions' => [
        'auvergne-rhone-alpes' => 'Auvergne-Rhône-Alpes',
        'bourgogne-franche-comte' => 'Bourgogne-Franche-Comté',
        'bretagne' => 'Bretagne',
        'centre-val-de-loire' => 'Centre-Val de Loire',
        'corse' => 'Corse',
        'grand-est' => 'Grand Est',
        'hauts-de-france' => 'Hauts-de-France',
        'ile-de-france' => 'Île-de-France',
        'normandie' => 'Normandie',
        'nouvelle-aquitaine' => 'Nouvelle-Aquitaine',
        'occitanie' => 'Occitanie',
        'pays-de-la-loire' => 'Pays de la Loire',
        'provence-alpes-cote-d-azur' => ['name' => "Provence-Alpes-Côte d'Azur", 'slug' => 'provence-alpes-cote-d-azur'],
        'guadeloupe' => 'Guadeloupe',
        'martinique' => 'Martinique',
        'guyane' => 'Guyane',
        'la-reunion' => 'La Réunion',
        'mayotte' => 'Mayotte',
        'saint-pierre-et-miquelon' => 'Saint-Pierre-et-Miquelon',
        'saint-barthelemy' => 'Saint-Barthélemy',
        'saint-martin' => 'Saint-Martin',
    ],

    'departments' => [
        '01' => ['name' => 'Ain', 'region' => 'auvergne-rhone-alpes'],
        '02' => ['name' => 'Aisne', 'region' => 'hauts-de-france'],
        '03' => ['name' => 'Allier', 'region' => 'auvergne-rhone-alpes'],
        '04' => ['name' => 'Alpes-de-Haute-Provence', 'region' => 'provence-alpes-cote-d-azur'],
        '05' => ['name' => 'Hautes-Alpes', 'region' => 'provence-alpes-cote-d-azur'],
        '06' => ['name' => 'Alpes-Maritimes', 'region' => 'provence-alpes-cote-d-azur'],
        '07' => ['name' => 'Ardèche', 'region' => 'auvergne-rhone-alpes'],
        '08' => ['name' => 'Ardennes', 'region' => 'grand-est'],
        '09' => ['name' => 'Ariège', 'region' => 'occitanie'],
        '10' => ['name' => 'Aube', 'region' => 'grand-est'],
        '11' => ['name' => 'Aude', 'region' => 'occitanie'],
        '12' => ['name' => 'Aveyron', 'region' => 'occitanie'],
        '13' => ['name' => 'Bouches-du-Rhône', 'region' => 'provence-alpes-cote-d-azur'],
        '14' => ['name' => 'Calvados', 'region' => 'normandie'],
        '15' => ['name' => 'Cantal', 'region' => 'auvergne-rhone-alpes'],
        '16' => ['name' => 'Charente', 'region' => 'nouvelle-aquitaine'],
        '17' => ['name' => 'Charente-Maritime', 'region' => 'nouvelle-aquitaine'],
        '18' => ['name' => 'Cher', 'region' => 'centre-val-de-loire'],
        '19' => ['name' => 'Corrèze', 'region' => 'nouvelle-aquitaine'],
        '21' => ['name' => "Côte-d'Or", 'region' => 'bourgogne-franche-comte'],
        '22' => ['name' => "Côtes-d'Armor", 'region' => 'bretagne'],
        '23' => ['name' => 'Creuse', 'region' => 'nouvelle-aquitaine'],
        '24' => ['name' => 'Dordogne', 'region' => 'nouvelle-aquitaine'],
        '25' => ['name' => 'Doubs', 'region' => 'bourgogne-franche-comte'],
        '26' => ['name' => 'Drôme', 'region' => 'auvergne-rhone-alpes'],
        '27' => ['name' => 'Eure', 'region' => 'normandie'],
        '28' => ['name' => 'Eure-et-Loir', 'region' => 'centre-val-de-loire'],
        '29' => ['name' => 'Finistère', 'region' => 'bretagne'],
        '2A' => ['name' => 'Corse-du-Sud', 'region' => 'corse'],
        '2B' => ['name' => 'Haute-Corse', 'region' => 'corse'],
        '30' => ['name' => 'Gard', 'region' => 'occitanie'],
        '31' => ['name' => 'Haute-Garonne', 'region' => 'occitanie'],
        '32' => ['name' => 'Gers', 'region' => 'occitanie'],
        '33' => ['name' => 'Gironde', 'region' => 'nouvelle-aquitaine'],
        '34' => ['name' => 'Hérault', 'region' => 'occitanie'],
        '35' => ['name' => 'Ille-et-Vilaine', 'region' => 'bretagne'],
        '36' => ['name' => 'Indre', 'region' => 'centre-val-de-loire'],
        '37' => ['name' => 'Indre-et-Loire', 'region' => 'centre-val-de-loire'],
        '38' => ['name' => 'Isère', 'region' => 'auvergne-rhone-alpes'],
        '39' => ['name' => 'Jura', 'region' => 'bourgogne-franche-comte'],
        '40' => ['name' => 'Landes', 'region' => 'nouvelle-aquitaine'],
        '41' => ['name' => 'Loir-et-Cher', 'region' => 'centre-val-de-loire'],
        '42' => ['name' => 'Loire', 'region' => 'auvergne-rhone-alpes'],
        '43' => ['name' => 'Haute-Loire', 'region' => 'auvergne-rhone-alpes'],
        '44' => ['name' => 'Loire-Atlantique', 'region' => 'pays-de-la-loire'],
        '45' => ['name' => 'Loiret', 'region' => 'centre-val-de-loire'],
        '46' => ['name' => 'Lot', 'region' => 'occitanie'],
        '47' => ['name' => 'Lot-et-Garonne', 'region' => 'nouvelle-aquitaine'],
        '48' => ['name' => 'Lozère', 'region' => 'occitanie'],
        '49' => ['name' => 'Maine-et-Loire', 'region' => 'pays-de-la-loire'],
        '50' => ['name' => 'Manche', 'region' => 'normandie'],
        '51' => ['name' => 'Marne', 'region' => 'grand-est'],
        '52' => ['name' => 'Haute-Marne', 'region' => 'grand-est'],
        '53' => ['name' => 'Mayenne', 'region' => 'pays-de-la-loire'],
        '54' => ['name' => 'Meurthe-et-Moselle', 'region' => 'grand-est'],
        '55' => ['name' => 'Meuse', 'region' => 'grand-est'],
        '56' => ['name' => 'Morbihan', 'region' => 'bretagne'],
        '57' => ['name' => 'Moselle', 'region' => 'grand-est'],
        '58' => ['name' => 'Nièvre', 'region' => 'bourgogne-franche-comte'],
        '59' => ['name' => 'Nord', 'region' => 'hauts-de-france'],
        '60' => ['name' => 'Oise', 'region' => 'hauts-de-france'],
        '61' => ['name' => 'Orne', 'region' => 'normandie'],
        '62' => ['name' => 'Pas-de-Calais', 'region' => 'hauts-de-france'],
        '63' => ['name' => 'Puy-de-Dôme', 'region' => 'auvergne-rhone-alpes'],
        '64' => ['name' => 'Pyrénées-Atlantiques', 'region' => 'nouvelle-aquitaine'],
        '65' => ['name' => 'Hautes-Pyrénées', 'region' => 'occitanie'],
        '66' => ['name' => 'Pyrénées-Orientales', 'region' => 'occitanie'],
        '67' => ['name' => 'Bas-Rhin', 'region' => 'grand-est'],
        '68' => ['name' => 'Haut-Rhin', 'region' => 'grand-est'],
        '69' => ['name' => 'Rhône', 'region' => 'auvergne-rhone-alpes'],
        '70' => ['name' => 'Haute-Saône', 'region' => 'bourgogne-franche-comte'],
        '71' => ['name' => 'Saône-et-Loire', 'region' => 'bourgogne-franche-comte'],
        '72' => ['name' => 'Sarthe', 'region' => 'pays-de-la-loire'],
        '73' => ['name' => 'Savoie', 'region' => 'auvergne-rhone-alpes'],
        '74' => ['name' => 'Haute-Savoie', 'region' => 'auvergne-rhone-alpes'],
        '75' => ['name' => 'Paris', 'region' => 'ile-de-france'],
        '76' => ['name' => 'Seine-Maritime', 'region' => 'normandie'],
        '77' => ['name' => 'Seine-et-Marne', 'region' => 'ile-de-france'],
        '78' => ['name' => 'Yvelines', 'region' => 'ile-de-france'],
        '79' => ['name' => 'Deux-Sèvres', 'region' => 'nouvelle-aquitaine'],
        '80' => ['name' => 'Somme', 'region' => 'hauts-de-france'],
        '81' => ['name' => 'Tarn', 'region' => 'occitanie'],
        '82' => ['name' => 'Tarn-et-Garonne', 'region' => 'occitanie'],
        '83' => ['name' => 'Var', 'region' => 'provence-alpes-cote-d-azur'],
        '84' => ['name' => 'Vaucluse', 'region' => 'provence-alpes-cote-d-azur'],
        '85' => ['name' => 'Vendée', 'region' => 'pays-de-la-loire'],
        '86' => ['name' => 'Vienne', 'region' => 'nouvelle-aquitaine'],
        '87' => ['name' => 'Haute-Vienne', 'region' => 'nouvelle-aquitaine'],
        '88' => ['name' => 'Vosges', 'region' => 'grand-est'],
        '89' => ['name' => 'Yonne', 'region' => 'bourgogne-franche-comte'],
        '90' => ['name' => 'Territoire de Belfort', 'region' => 'bourgogne-franche-comte'],
        '91' => ['name' => 'Essonne', 'region' => 'ile-de-france'],
        '92' => ['name' => 'Hauts-de-Seine', 'region' => 'ile-de-france'],
        '93' => ['name' => 'Seine-Saint-Denis', 'region' => 'ile-de-france'],
        '94' => ['name' => 'Val-de-Marne', 'region' => 'ile-de-france'],
        '95' => [ 'name' => "Val-d'Oise", 'region' => 'ile-de-france'],
        '971' => ['name' => 'Guadeloupe', 'region' => 'guadeloupe'],
        '972' => ['name' => 'Martinique', 'region' => 'martinique'],
        '973' => ['name' => 'Guyane', 'region' => 'guyane'],
        '974' => ['name' => 'La Réunion', 'region' => 'la-reunion'],
        '975' => ['name' => 'Saint-Pierre-et-Miquelon', 'region' => 'saint-pierre-et-miquelon'],
        '976' => ['name' => 'Mayotte', 'region' => 'mayotte'],
        '977' => ['name' => 'Saint-Barthélemy', 'region' => 'saint-barthelemy'],
        '978' => ['name' => 'Saint-Martin', 'region' => 'saint-martin'],
    ],
];
