<?php
namespace App\Filament\Resources;
use App\Filament\Forms\Components\EditorialRichEditor; use App\Filament\Resources\ArticleResource\Pages; use App\Filament\Support\EditorialSidebarFields; use App\Models\Article; use App\Services\EditorialTrash; use Filament\Actions\{Action,EditAction}; use Filament\Forms\Components\{Select,Textarea,TextInput,Toggle}; use Filament\Schemas\Components\{Section,Tabs}; use Filament\Schemas\Schema; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Filters\SelectFilter; use Filament\Tables\Table; use Illuminate\Support\Str;
class ArticleResource extends AdminResource
{
 protected static ?string $model=Article::class; protected static ?string $recordTitleAttribute='title'; protected static string|null|\BackedEnum $navigationIcon='heroicon-o-newspaper'; protected static string|\UnitEnum|null $navigationGroup='Contenu'; protected static ?int $navigationSort=2; protected static ?string $navigationLabel='Articles'; public static function getGloballySearchableAttributes():array{return ['title','slug'];}
 public static function form(Schema $schema):Schema{return $schema->components([Tabs::make('Article')->tabs([Tabs\Tab::make('Éditorial')->schema([Section::make()->columns(2)->schema([TextInput::make('title')->required()->maxLength(255)->live(onBlur:true)->afterStateUpdated(function($state,$set,string $operation):void{if($operation==='create')$set('slug',Str::slug((string)$state));}),TextInput::make('slug')->required()->alphaDash()->unique(ignoreRecord:true)->helperText('Généré à la création. Une modification manuelle crée une redirection 301 depuis l’ancienne URL.'),Select::make('status')->options(['draft'=>'Brouillon','published'=>'Publié'])->default('draft')->required(),TextInput::make('published_at')->label('Publication')->type('datetime-local'),Textarea::make('excerpt')->label('Extrait')->rows(3)->maxLength(1000)->columnSpanFull(),EditorialRichEditor::make('content_html')->label('Contenu')->extraAttributes(['class'=>'editorial-rich-editor'])->columnSpanFull()->required()])]),Tabs\Tab::make('Taxonomies')->schema([Section::make()->columns(2)->schema([Select::make('categories')->relationship('categories','name')->multiple()->searchable()->preload(),Select::make('tags')->relationship('tags','name')->multiple()->searchable()->preload()])]),Tabs\Tab::make('Sidebar')->schema([EditorialSidebarFields::section()]),Tabs\Tab::make('SEO')->schema([Section::make()->schema([TextInput::make('seo_title')->maxLength(255),Textarea::make('seo_description')->rows(3)->maxLength(500),TextInput::make('seo_robots')->maxLength(100)])]),Tabs\Tab::make('IA & système')->schema([Section::make()->columns(2)->schema([Select::make('source_type')->options(['manual'=>'Manuel','ai'=>'IA','legacy'=>'Migration legacy'])->default('manual'),Toggle::make('ai_disclosure_visible')->label('Afficher la provenance IA'),TextInput::make('legacy_wp_id')->disabled()->dehydrated(false)->visibleOn('edit')])])])->columnSpanFull()]);}
 public static function trash(Article $article,array $data):void{app(EditorialTrash::class)->trash($article,(int)$data['status_code'],$data['destination']??null);} public static function restore(Article $article):void{app(EditorialTrash::class)->restore($article);} public static function forceDelete(Article $article):void{app(EditorialTrash::class)->forceDelete($article);}
 public static function trashAction():Action{return Action::make('trash')->label('Supprimer')->icon('heroicon-o-trash')->color('danger')->modalHeading('Supprimer ce contenu')->modalDescription('Que doit devenir l’ancienne URL ?')->modalSubmitActionLabel('Mettre à la corbeille')->form([Select::make('status_code')->label('Comportement de l’ancienne URL')->options([301=>'301 — Redirection permanente',302=>'302 — Redirection temporaire',404=>'404 — Page introuvable',410=>'410 — Contenu supprimé définitivement'])->required()->live(),TextInput::make('destination')->label('URL de destination')->visible(fn($get):bool=>in_array((int)$get('status_code'),[301,302],true))->required(fn($get):bool=>in_array((int)$get('status_code'),[301,302],true))->maxLength(2048)])->visible(fn(Article $article):bool=>!$article->trashed())->action(fn(Article $article,array $data)=>static::trash($article,$data));}
 public static function restoreAction():Action{return Action::make('restore')->label('Restaurer')->color('success')->visible(fn(Article $article):bool=>$article->trashed())->action(fn(Article $article)=>static::restore($article));} public static function forceDeleteAction():Action{return Action::make('force_delete')->label('Supprimer définitivement')->color('danger')->requiresConfirmation()->visible(fn(Article $article):bool=>$article->trashed())->action(fn(Article $article)=>static::forceDelete($article));}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('title')->label('Titre')->searchable()->sortable()->description(fn(Article $a)=>$a->slug),TextColumn::make('status')->badge()->color(fn($state)=>$state==='published'?'success':'gray')->sortable(),TextColumn::make('source_type')->label('Source')->badge()->toggleable(),TextColumn::make('published_at')->label('Publication')->dateTime('d/m/Y H:i')->placeholder('—')->sortable(),TextColumn::make('legacy_modified_at')->label('Modifié (legacy)')->dateTime('d/m/Y H:i')->placeholder('—')->sortable()->toggleable()])->filters([SelectFilter::make('status')->options(['draft'=>'Brouillon','published'=>'Publié']),SelectFilter::make('source_type')->options(['manual'=>'Manuel','ai'=>'IA','legacy'=>'Migration legacy'])])->recordActions([static::viewOnSiteAction()->visible(fn(Article $a):bool=>!$a->trashed()),EditAction::make()->visible(fn(Article $a):bool=>!$a->trashed()),static::trashAction(),static::restoreAction(),static::forceDeleteAction()])->toolbarActions([\Filament\Actions\BulkActionGroup::make([\Filament\Actions\BulkAction::make('trash_404')->label('Corbeille (404)')->requiresConfirmation()->action(fn($records)=>$records->each(fn(Article $a)=>static::trash($a,['status_code'=>404]))),\Filament\Actions\BulkAction::make('trash_410')->label('Corbeille (410)')->requiresConfirmation()->action(fn($records)=>$records->each(fn(Article $a)=>static::trash($a,['status_code'=>410]))),\Filament\Actions\BulkAction::make('restore')->label('Restaurer')->action(fn($records)=>$records->each(fn(Article $a)=>static::restore($a))),\Filament\Actions\BulkAction::make('force_delete')->label('Supprimer définitivement')->requiresConfirmation()->action(fn($records)=>$records->each(fn(Article $a)=>static::forceDelete($a)))])])->defaultSort('published_at','desc')->emptyStateHeading('Aucun article');}
 public static function getPages():array{return ['index'=>Pages\ListArticles::route('/'),'create'=>Pages\CreateArticle::route('/create'),'edit'=>Pages\EditArticle::route('/{record}/edit')];}
}
