<?php
namespace App\Filament\Resources;
use App\Filament\Resources\ArticleResource\Pages; use App\Models\Article; use Filament\Actions\EditAction; use Filament\Forms\Components\{RichEditor,Select,Textarea,TextInput,Toggle}; use Filament\Schemas\Components\{Section,Tabs}; use Filament\Schemas\Schema; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Filters\SelectFilter; use Filament\Tables\Table; use Illuminate\Support\Str;
class ArticleResource extends AdminResource
{
 protected static ?string $model=Article::class; protected static ?string $recordTitleAttribute='title'; protected static string|null|\BackedEnum $navigationIcon='heroicon-o-newspaper'; protected static string|\UnitEnum|null $navigationGroup='Contenu'; protected static ?int $navigationSort=2; protected static ?string $navigationLabel='Articles'; public static function getGloballySearchableAttributes():array{return ['title','slug'];}
 public static function form(Schema $schema):Schema{return $schema->components([Tabs::make('Article')->tabs([Tabs\Tab::make('Éditorial')->schema([Section::make()->columns(2)->schema([TextInput::make('title')->required()->maxLength(255)->live(onBlur:true)->afterStateUpdated(fn($state,$set)=>$set('slug',Str::slug((string)$state))),TextInput::make('slug')->required()->alphaDash()->unique(ignoreRecord:true),Select::make('status')->options(['draft'=>'Brouillon','published'=>'Publié'])->default('draft')->required(),TextInput::make('published_at')->label('Publication')->type('datetime-local'),Textarea::make('excerpt')->label('Extrait')->rows(3)->maxLength(1000)->columnSpanFull(),RichEditor::make('content_html')->label('Contenu')->columnSpanFull()->required()])]),Tabs\Tab::make('Taxonomies')->schema([Section::make()->columns(2)->schema([Select::make('categories')->relationship('categories','name')->multiple()->searchable()->preload(),Select::make('tags')->relationship('tags','name')->multiple()->searchable()->preload()])]),Tabs\Tab::make('SEO')->schema([Section::make()->schema([TextInput::make('seo_title')->maxLength(255),Textarea::make('seo_description')->rows(3)->maxLength(500),TextInput::make('seo_robots')->maxLength(100)])]),Tabs\Tab::make('IA & système')->schema([Section::make()->columns(2)->schema([Select::make('source_type')->options(['manual'=>'Manuel','ai'=>'IA','legacy'=>'Migration legacy'])->default('manual'),Toggle::make('ai_disclosure_visible')->label('Afficher la provenance IA'),TextInput::make('legacy_wp_id')->disabled()->dehydrated(false)->visibleOn('edit')])])])->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('title')->label('Titre')->searchable()->sortable()->description(fn(Article $a)=>$a->slug),TextColumn::make('status')->badge()->color(fn($state)=>$state==='published'?'success':'gray')->sortable(),TextColumn::make('source_type')->label('Source')->badge()->toggleable(),TextColumn::make('published_at')->label('Publication')->dateTime('d/m/Y H:i')->placeholder('—')->sortable(),TextColumn::make('legacy_modified_at')->label('Modifié (legacy)')->dateTime('d/m/Y H:i')->placeholder('—')->sortable()->toggleable()])->filters([SelectFilter::make('status')->options(['draft'=>'Brouillon','published'=>'Publié']),SelectFilter::make('source_type')->options(['manual'=>'Manuel','ai'=>'IA','legacy'=>'Migration legacy'])])->recordActions([static::viewOnSiteAction(), EditAction::make()])->defaultSort('published_at','desc')->emptyStateHeading('Aucun article');}
 public static function getPages():array{return ['index'=>Pages\ListArticles::route('/'),'create'=>Pages\CreateArticle::route('/create'),'edit'=>Pages\EditArticle::route('/{record}/edit')];}
}
