<?php
namespace App\Filament\Resources;
use App\Models\EmailTemplate; use App\Services\{EmailTemplateRegistry,TransactionalMailService}; use Filament\Actions\{Action,CreateAction,EditAction}; use Filament\Forms\Components\{Placeholder,Textarea,TextInput,Toggle}; use Filament\Schemas\Components\Section; use Filament\Schemas\Schema; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Table;
class EmailTemplateResource extends AdminResource
{
 protected static ?string $model=EmailTemplate::class; protected static ?string $recordTitleAttribute='key'; protected static string|null|\BackedEnum $navigationIcon='heroicon-o-document-text'; protected static string|\UnitEnum|null $navigationGroup='Emails'; protected static ?string $navigationLabel='Templates'; protected static ?int $navigationSort=2;
 public static function canCreate():bool{return false;} public static function form(Schema $schema):Schema{return $schema->components([Section::make()->schema([TextInput::make('key')->disabled()->dehydrated(false),Placeholder::make('available_variables')->label('Variables autorisées')->content(fn(?EmailTemplate $record)=>$record ? implode(', ',array_map(fn($v)=>'{{ '.$v.' }}',app(EmailTemplateRegistry::class)->get($record->key)['variables'])) : ''),TextInput::make('subject')->label('Objet')->required()->maxLength(255),Textarea::make('body')->label('Contenu')->required()->rows(12)->helperText('Texte simple uniquement. Les variables non autorisées restent affichées telles quelles.'),TextInput::make('cta_label')->label('Texte du bouton')->maxLength(120),Toggle::make('is_active')->label('Actif')->default(true)])]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('key')->label('Identifiant')->searchable(),TextColumn::make('key')->label('Nom')->formatStateUsing(fn($s)=>app(EmailTemplateRegistry::class)->all()[$s]['name'] ?? (string) $s),TextColumn::make('is_active')->badge()->formatStateUsing(fn($s)=>$s?'Actif':'Inactif')])->recordActions([Action::make('preview')->label('Aperçu')->modalContent(fn(EmailTemplate $r)=>view('emails.transactional',['email'=>app(\App\Services\EmailTemplateRenderer::class)->render($r->key,collect(app(EmailTemplateRegistry::class)->get($r->key)['variables'])->mapWithKeys(fn($v)=>[$v=>'Exemple'])->all())]))->modalSubmitAction(false),Action::make('test')->label('Envoyer un test')->form([TextInput::make('email')->email()->required()])->action(fn(EmailTemplate $r,array $data)=>app(TransactionalMailService::class)->queue($r->key,$data['email'],collect(app(EmailTemplateRegistry::class)->get($r->key)['variables'])->mapWithKeys(fn($v)=>[$v=>'Exemple'])->all())),EditAction::make()])->defaultSort('key');}
 public static function getPages():array{return ['index'=>EmailTemplateResource\Pages\ListEmailTemplates::route('/'),'edit'=>EmailTemplateResource\Pages\EditEmailTemplate::route('/{record}/edit')];}
}
