<?php
namespace App\Filament\Resources;
use App\Filament\Resources\MediaAssetResource\Pages; use App\Models\MediaAsset; use Filament\Actions\EditAction; use Filament\Forms\Components\{FileUpload,Textarea,TextInput}; use Filament\Schemas\Components\Section; use Filament\Schemas\Schema; use Filament\Tables\Columns\{ImageColumn,TextColumn}; use Filament\Tables\Filters\SelectFilter; use Filament\Tables\Table; use Illuminate\Database\Eloquent\Builder;
class MediaAssetResource extends AdminResource
{
 protected static ?string $model=MediaAsset::class; protected static ?string $recordTitleAttribute='alt_text'; protected static string|null|\BackedEnum $navigationIcon='heroicon-o-photo'; protected static string|\UnitEnum|null $navigationGroup='Contenu'; protected static ?int $navigationSort=4; protected static ?string $navigationLabel='Médias'; public static function canCreate():bool{return false;} public static function getEloquentQuery():Builder{return parent::getEloquentQuery()->withCount('variants');}
 public static function form(Schema $schema):Schema{return $schema->components([Section::make('Métadonnées')->schema([TextInput::make('alt_text')->label('Texte alternatif')->maxLength(255),Textarea::make('caption')->label('Légende')->maxLength(1000)->rows(3),TextInput::make('mime')->disabled()->dehydrated(false),TextInput::make('dimensions')->disabled()->dehydrated(false)->formatStateUsing(fn($record)=>$record?->width.' × '.$record?->height.' px'),TextInput::make('bytes')->disabled()->dehydrated(false)->formatStateUsing(fn($state)=>number_format((int)$state/1024,1,',',' ').' Ko')])->columns(2)]);}
 public static function table(Table $table):Table{return $table->columns([ImageColumn::make('preview')->label('Aperçu')->getStateUsing(fn(MediaAsset $a)=>route('media.show',$a))->square(),TextColumn::make('alt_text')->label('Texte alternatif')->searchable()->placeholder('Sans texte alternatif')->wrap(),TextColumn::make('mime')->label('Type')->badge(),TextColumn::make('dimensions')->label('Dimensions')->state(fn(MediaAsset $a)=>$a->width.' × '.$a->height),TextColumn::make('bytes')->label('Poids')->formatStateUsing(fn($state)=>number_format((int)$state/1024,1,',',' ').' Ko')->sortable(),TextColumn::make('variants_count')->label('Formats')->numeric()->toggleable(),TextColumn::make('created_at')->label('Ajouté')->since()->sortable()])->filters([SelectFilter::make('mime')->options(['image/jpeg'=>'JPEG','image/png'=>'PNG','image/webp'=>'WebP'])])->recordActions([EditAction::make()])->defaultSort('created_at','desc')->emptyStateHeading('Votre médiathèque est vide');}
 public static function getPages():array{return ['index'=>Pages\ListMediaAssets::route('/'),'edit'=>Pages\EditMediaAsset::route('/{record}/edit')];}
}
