<?php
namespace App\Filament\Resources;
use App\Filament\Forms\Components\EditorialRichEditor; use App\Filament\Resources\PageResource\Pages; use App\Filament\Support\EditorialSidebarFields; use App\Models\Page; use App\Services\EditorialTrash; use Filament\Actions\{Action,EditAction}; use Filament\Forms\Components\{Select,Textarea,TextInput,Toggle}; use Filament\Schemas\Components\{Section,Tabs}; use Filament\Schemas\Schema; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Filters\SelectFilter; use Filament\Tables\Table; use Illuminate\Support\Str;
class PageResource extends AdminResource
{
 protected static ?string $model=Page::class; protected static ?string $recordTitleAttribute='title'; protected static string|null|\BackedEnum $navigationIcon='heroicon-o-document-text'; protected static string|\UnitEnum|null $navigationGroup='Contenu'; protected static ?int $navigationSort=3; protected static ?string $navigationLabel='Pages'; public static function getGloballySearchableAttributes():array{return ['title','slug'];}
 public static function form(Schema $schema):Schema{return $schema->components([Tabs::make('Page')->tabs([Tabs\Tab::make('Contenu')->schema([Section::make()->columns(2)->schema([TextInput::make('title')->required()->maxLength(255)->live(onBlur:true)->afterStateUpdated(function($state,$set,string $operation):void{if($operation==='create')$set('slug',Str::slug((string)$state));}),TextInput::make('slug')->required()->alphaDash()->unique(ignoreRecord:true)->helperText('Généré à la création. Une modification manuelle crée une redirection 301 depuis l’ancienne URL.'),Select::make('status')->options(['draft'=>'Brouillon','published'=>'Publié'])->default('draft')->required(),TextInput::make('published_at')->type('datetime-local')->label('Publication'),Textarea::make('excerpt')->rows(3)->maxLength(1000)->columnSpanFull(),EditorialRichEditor::make('content_html')->label('Contenu')->extraAttributes(['class'=>'editorial-rich-editor'])->columnSpanFull()->required()])]),Tabs\Tab::make('Sidebar')->schema([Section::make('Activation')->schema([Toggle::make('editorial_sidebar_enabled')->label('Afficher la sidebar éditoriale')->default(false)->helperText('Désactivée par défaut pour les Pages.')]),EditorialSidebarFields::section()]),Tabs\Tab::make('SEO')->schema([Section::make()->schema([TextInput::make('seo_title')->maxLength(255),Textarea::make('seo_description')->rows(3)->maxLength(500),TextInput::make('seo_robots')->maxLength(100)])]),Tabs\Tab::make('Système')->schema([Section::make()->columns(2)->schema([Select::make('source_type')->options(['manual'=>'Manuel','ai'=>'IA','legacy'=>'Migration legacy'])->default('manual'),Toggle::make('ai_disclosure_visible')->label('Afficher la provenance IA'),TextInput::make('legacy_wp_id')->disabled()->dehydrated(false)->visibleOn('edit')])])])->columnSpanFull()]);}
 public static function trash(Page $page,array $data):void{app(EditorialTrash::class)->trash($page,(int)$data['status_code'],$data['destination']??null);} public static function restore(Page $page):void{app(EditorialTrash::class)->restore($page);} public static function forceDelete(Page $page):void{app(EditorialTrash::class)->forceDelete($page);}
 public static function trashAction():Action{return Action::make('trash')->label('Supprimer')->icon('heroicon-o-trash')->color('danger')->modalHeading('Supprimer ce contenu')->modalDescription('Que doit devenir l’ancienne URL ?')->modalSubmitActionLabel('Mettre à la corbeille')->form([Select::make('status_code')->label('Comportement de l’ancienne URL')->options([301=>'301 — Redirection permanente',302=>'302 — Redirection temporaire',404=>'404 — Page introuvable',410=>'410 — Contenu supprimé définitivement'])->required()->live(),TextInput::make('destination')->label('URL de destination')->visible(fn($get):bool=>in_array((int)$get('status_code'),[301,302],true))->required(fn($get):bool=>in_array((int)$get('status_code'),[301,302],true))->maxLength(2048)])->visible(fn(Page $page):bool=>!$page->trashed())->action(fn(Page $page,array $data)=>static::trash($page,$data));}
 public static function restoreAction():Action{return Action::make('restore')->label('Restaurer')->color('success')->visible(fn(Page $page):bool=>$page->trashed())->action(fn(Page $page)=>static::restore($page));} public static function forceDeleteAction():Action{return Action::make('force_delete')->label('Supprimer définitivement')->color('danger')->requiresConfirmation()->visible(fn(Page $page):bool=>$page->trashed())->action(fn(Page $page)=>static::forceDelete($page));}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('title')->label('Titre')->searchable()->sortable()->description(fn(Page $p)=>$p->slug),TextColumn::make('status')->badge()->color(fn($state)=>$state==='published'?'success':'gray')->sortable(),TextColumn::make('published_at')->label('Publication')->dateTime('d/m/Y H:i')->placeholder('—')->sortable(),TextColumn::make('legacy_modified_at')->label('Modifié (legacy)')->dateTime('d/m/Y H:i')->placeholder('—')->sortable()->toggleable()])->filters([SelectFilter::make('status')->options(['draft'=>'Brouillon','published'=>'Publié'])])->recordActions([static::viewOnSiteAction()->visible(fn(Page $p):bool=>!$p->trashed()),EditAction::make()->visible(fn(Page $p):bool=>!$p->trashed()),static::trashAction(),static::restoreAction(),static::forceDeleteAction()])->toolbarActions([\Filament\Actions\BulkActionGroup::make([\Filament\Actions\BulkAction::make('trash_404')->label('Corbeille (404)')->requiresConfirmation()->action(fn($records)=>$records->each(fn(Page $p)=>static::trash($p,['status_code'=>404]))),\Filament\Actions\BulkAction::make('trash_410')->label('Corbeille (410)')->requiresConfirmation()->action(fn($records)=>$records->each(fn(Page $p)=>static::trash($p,['status_code'=>410]))),\Filament\Actions\BulkAction::make('restore')->label('Restaurer')->action(fn($records)=>$records->each(fn(Page $p)=>static::restore($p))),\Filament\Actions\BulkAction::make('force_delete')->label('Supprimer définitivement')->requiresConfirmation()->action(fn($records)=>$records->each(fn(Page $p)=>static::forceDelete($p)))])])->defaultSort('updated_at','desc')->emptyStateHeading('Aucune page');}
 public static function getPages():array{return ['index'=>Pages\ListPages::route('/'),'create'=>Pages\CreatePage::route('/create'),'edit'=>Pages\EditPage::route('/{record}/edit')];}
}
