<?php
namespace App\Filament\Resources;
use App\Filament\Resources\PageResource\Pages; use App\Models\Page; use Filament\Actions\EditAction; use Filament\Forms\Components\{RichEditor,Select,Textarea,TextInput,Toggle}; use Filament\Schemas\Components\{Section,Tabs}; use Filament\Schemas\Schema; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Filters\SelectFilter; use Filament\Tables\Table; use Illuminate\Support\Str;
class PageResource extends AdminResource
{
 protected static ?string $model=Page::class; protected static ?string $recordTitleAttribute='title'; protected static string|null|\BackedEnum $navigationIcon='heroicon-o-document-text'; protected static string|\UnitEnum|null $navigationGroup='Contenu'; protected static ?int $navigationSort=3; protected static ?string $navigationLabel='Pages'; public static function getGloballySearchableAttributes():array{return ['title','slug'];}
 public static function form(Schema $schema):Schema{return $schema->components([Tabs::make('Page')->tabs([Tabs\Tab::make('Contenu')->schema([Section::make()->columns(2)->schema([TextInput::make('title')->required()->maxLength(255)->live(onBlur:true)->afterStateUpdated(fn($state,$set)=>$set('slug',Str::slug((string)$state))),TextInput::make('slug')->required()->alphaDash()->unique(ignoreRecord:true),Select::make('status')->options(['draft'=>'Brouillon','published'=>'Publié'])->default('draft')->required(),TextInput::make('published_at')->type('datetime-local')->label('Publication'),Textarea::make('excerpt')->rows(3)->maxLength(1000)->columnSpanFull(),RichEditor::make('content_html')->label('Contenu')->columnSpanFull()->required()])]),Tabs\Tab::make('SEO')->schema([Section::make()->schema([TextInput::make('seo_title')->maxLength(255),Textarea::make('seo_description')->rows(3)->maxLength(500),TextInput::make('seo_robots')->maxLength(100)])]),Tabs\Tab::make('Système')->schema([Section::make()->columns(2)->schema([Select::make('source_type')->options(['manual'=>'Manuel','ai'=>'IA','legacy'=>'Migration legacy'])->default('manual'),Toggle::make('ai_disclosure_visible')->label('Afficher la provenance IA'),TextInput::make('legacy_wp_id')->disabled()->dehydrated(false)->visibleOn('edit')])])])->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('title')->label('Titre')->state(fn(Page $p)=>html_entity_decode($p->title, ENT_QUOTES | ENT_HTML5, 'UTF-8'))->searchable()->sortable()->description(fn(Page $p)=>$p->slug),TextColumn::make('status')->badge()->color(fn($s)=>$s==='published'?'success':'gray')->sortable(),TextColumn::make('published_at')->label('Publication')->dateTime('d/m/Y')->sortable(),TextColumn::make('updated_at')->label('Modifié')->since()->sortable()->toggleable()])->filters([SelectFilter::make('status')->options(['draft'=>'Brouillon','published'=>'Publié'])])->recordActions([EditAction::make()])->defaultSort('updated_at','desc')->emptyStateHeading('Aucune page');}
 public static function getPages():array{return ['index'=>Pages\ListPages::route('/'),'create'=>Pages\CreatePage::route('/create'),'edit'=>Pages\EditPage::route('/{record}/edit')];}
}
