<?php
namespace App\Filament\Resources;
use App\Models\RestaurantClaim; use App\Services\ClaimModeration; use Filament\Actions\{Action,BulkAction,BulkActionGroup,EditAction}; use Filament\Forms\Components\Textarea; use Filament\Schemas\Schema; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Filters\SelectFilter; use Filament\Tables\Table; use Illuminate\Database\Eloquent\Builder;
class RestaurantClaimResource extends AdminResource {
 protected static ?string $model=RestaurantClaim::class; protected static ?string $modelLabel='revendication'; protected static ?string $pluralModelLabel='Claims'; protected static ?string $recordTitleAttribute='id'; protected static string|null|\BackedEnum $navigationIcon='heroicon-o-shield-check'; protected static string|\UnitEnum|null $navigationGroup='Communauté'; protected static ?int $navigationSort=3; protected static ?string $navigationLabel='Claims';
 public static function canCreate():bool{return false;}
 public static function getEloquentQuery():Builder{return parent::getEloquentQuery()->with(['restaurant','user']);}
 public static function form(Schema $schema):Schema{return $schema->components([Textarea::make('full_name')->label('Nom / prénom')->disabled(),Textarea::make('email')->label('E-mail')->disabled(),Textarea::make('company')->label('Société')->disabled(),Textarea::make('siret')->label('SIRET')->disabled(),Textarea::make('message')->label('Demande')->disabled()->columnSpanFull(),Textarea::make('admin_note')->label('Note de modération')->maxLength(1000)->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('restaurant.name')->label('Restaurant')->searchable()->sortable(),TextColumn::make('email')->label('E-mail')->searchable()->description(fn(RestaurantClaim $c)=>$c->user?->name),TextColumn::make('full_name')->label('Nom / prénom')->toggleable(),TextColumn::make('company')->label('Société')->toggleable(),TextColumn::make('siret')->label('SIRET')->toggleable(),TextColumn::make('certified')->label('Certification')->formatStateUsing(fn(bool $state)=>$state?'Oui':'Non'),TextColumn::make('status')->badge()->color(fn(string $state)=>$state==='approved'?'success':(in_array($state,['pending','pending_email_verification'])?'warning':'danger'))->sortable(),TextColumn::make('submitted_at')->label('Reçue')->dateTime('d/m/Y H:i')->sortable(),TextColumn::make('email_verified_at')->label('E-mail confirmé')->dateTime('d/m/Y H:i')->toggleable(),TextColumn::make('reviewed_at')->label('Traitée')->since()->toggleable()])->filters([SelectFilter::make('status')->default('pending')->options(['pending_email_verification'=>'À confirmer par e-mail','pending'=>'À valider','approved'=>'Approuvée','rejected'=>'Refusée','pending_publication'=>'En attente de publication'])])->recordActions([Action::make('identity_document')->label('Pièce d’identité')->url(fn(RestaurantClaim $c)=>route('claims.identity-document',$c))->openUrlInNewTab()->visible(fn(RestaurantClaim $c)=>filled($c->identity_document_path)),Action::make('approve')->label('Valider')->color('success')->requiresConfirmation()->visible(fn(RestaurantClaim $c)=>$c->status==='pending')->action(fn(RestaurantClaim $c)=>app(ClaimModeration::class)->approve($c)),Action::make('reject')->label('Refuser')->color('danger')->requiresConfirmation()->form([Textarea::make('admin_note')->label('Motif interne / message au demandeur')->maxLength(1000)])->visible(fn(RestaurantClaim $c)=>$c->status==='pending')->action(fn(RestaurantClaim $c,array $data)=>app(ClaimModeration::class)->reject($c,$data['admin_note']??null)),EditAction::make()->label('Détail')])->toolbarActions([BulkActionGroup::make([BulkAction::make('approve')->label('Approuver la sélection')->requiresConfirmation()->action(fn($records)=>$records->each(fn(RestaurantClaim $c)=>app(ClaimModeration::class)->approve($c)))])])->defaultSort('submitted_at')->emptyStateHeading('Aucune revendication dans cette file');}
 public static function getPages():array{return ['index'=>RestaurantClaimResource\Pages\ListRestaurantClaims::route('/')];}
}
