<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\RedirectRule; use App\Services\{AdminAudit,RedirectResolver}; use Illuminate\Http\Request;
class RedirectController extends Controller {
 public function index(Request $r){$q=RedirectRule::query();if($r->filled('q'))$q->where(fn($x)=>$x->where('source_path','like','%'.$r->q.'%')->orWhere('destination','like','%'.$r->q.'%'));return view('admin.redirects.index',['rules'=>$q->orderBy('priority')->paginate(30)->withQueryString()]);}
 public function create(){return view('admin.redirects.form',['rule'=>new RedirectRule(['match_type'=>'exact','status_code'=>301,'priority'=>1000,'is_active'=>true])]);}public function edit(RedirectRule $rule){return view('admin.redirects.form',compact('rule'));}
 public function store(Request $r,AdminAudit $audit){$rule=RedirectRule::create($this->data($r));$audit->record('redirect.created',$rule);return redirect()->route('admin.redirects.edit',$rule)->with('status','Redirection créée.');}public function update(Request $r,RedirectRule $rule,AdminAudit $audit){$rule->update($this->data($r));$audit->record('redirect.updated',$rule,$rule->getChanges());return back()->with('status','Redirection enregistrée.');}public function destroy(RedirectRule $rule,AdminAudit $audit){$rule->update(['is_active'=>false]);$audit->record('redirect.disabled',$rule);return back()->with('status','Redirection désactivée.');}
 public function test(Request $r,RedirectResolver $resolver){$d=$r->validate(['url'=>'required|string|max:2048']);$request=Request::create($d['url'],'GET');return back()->with('test',$resolver->resolve($request)?:['result'=>'Aucune règle applicable']);}
 private function data(Request $r):array{$d=$r->validate(['source_path'=>'required|string|max:2048','match_type'=>'required|in:exact,regex','query_pattern'=>'nullable|string|max:2048','destination'=>'required|string|max:2048','status_code'=>'required|in:301,302,307,308,410','priority'=>'required|integer|min:0|max:100000','is_active'=>'nullable|boolean','preserve_query'=>'nullable|boolean']);if($d['match_type']==='regex'&&@preg_match('~'.$d['source_path'].'~u','')===false)throw \Illuminate\Validation\ValidationException::withMessages(['source_path'=>'Expression régulière invalide.']);if($d['match_type']==='exact'&&!str_starts_with($d['source_path'],'/'))throw \Illuminate\Validation\ValidationException::withMessages(['source_path'=>'Le chemin doit commencer par /.']);$d['origin']='manual';$d['is_active']=$r->boolean('is_active');$d['preserve_query']=$r->boolean('preserve_query');return $d;}
}
