<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\{Category,Feature,Location,Restaurant,RestaurantOutboundLink}; use App\Services\AdminAudit; use Illuminate\Http\Request; use Illuminate\Support\Str;
class RestaurantController extends Controller {
 public function index(Request $r) { $q=Restaurant::query()->with('categories'); if($r->filled('q'))$q->where(fn($x)=>$x->where('name','like','%'.$r->q.'%')->orWhere('city_name','like','%'.$r->q.'%'));if($r->filled('status'))$q->where('status',$r->status);return view('admin.restaurants.index',['restaurants'=>$q->latest()->paginate(25)->withQueryString()]);}
 public function create(){return $this->form(new Restaurant(['status'=>'draft']));} public function edit(Restaurant $restaurant){return $this->form($restaurant->load(['categories','features','locations','outboundLinks']));}
 public function store(Request $r,AdminAudit $audit){$restaurant=Restaurant::create($this->data($r));$this->relations($r,$restaurant);$audit->record('restaurant.created',$restaurant);return redirect()->route('admin.restaurants.edit',$restaurant)->with('status','Restaurant créé.');}
 public function update(Request $r,Restaurant $restaurant,AdminAudit $audit){$restaurant->update($this->data($r,$restaurant));$this->relations($r,$restaurant);$audit->record('restaurant.updated',$restaurant,$restaurant->getChanges());return back()->with('status','Restaurant enregistré.');}
 public function archive(Restaurant $restaurant,AdminAudit $audit){$restaurant->update(['status'=>'archived']);$audit->record('restaurant.archived',$restaurant);return back()->with('status','Restaurant archivé.');}
 private function form(Restaurant $restaurant){return view('admin.restaurants.form',compact('restaurant')+['categories'=>Category::orderBy('name')->get(),'features'=>Feature::orderBy('name')->get(),'locations'=>Location::orderBy('name')->get()]);}
 private function data(Request $r,?Restaurant $restaurant=null):array{$d=$r->validate(['name'=>'required|string|max:255','slug'=>'nullable|alpha_dash|max:255|unique:restaurants,slug'.($restaurant?', '.$restaurant->id:''),'description'=>'nullable|string|max:20000','status'=>'required|in:draft,pending,published,reported,archived','address'=>'nullable|string|max:255','postal_code'=>'nullable|string|max:20','city_name'=>'nullable|string|max:255','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','phone'=>'nullable|string|max:100','contact_email'=>'nullable|email|max:255','seo_title'=>'nullable|string|max:255','seo_description'=>'nullable|string|max:500']);$d['slug']=$d['slug']?:Str::slug($d['name']);if(Restaurant::where('slug',$d['slug'])->when($restaurant,fn($q)=>$q->whereKeyNot($restaurant->id))->exists())throw \Illuminate\Validation\ValidationException::withMessages(['slug'=>'Ce slug existe déjà.']);if(!$restaurant)$d['legacy_wp_id']=random_int(1_000_000_000,2_000_000_000);return $d;}
 private function relations(Request $r,Restaurant $restaurant):void{$d=$r->validate(['categories'=>'array','categories.*'=>'integer|exists:categories,id','features'=>'array','features.*'=>'integer|exists:features,id','locations'=>'array','locations.*'=>'integer|exists:locations,id','external_label'=>'nullable|string|max:80','external_url'=>'nullable|url|max:2048']);$restaurant->categories()->sync($d['categories']??[]);$restaurant->features()->sync($d['features']??[]);$restaurant->locations()->sync($d['locations']??[]);if(!empty($d['external_url']))RestaurantOutboundLink::updateOrCreate(['restaurant_id'=>$restaurant->id,'label'=>$d['external_label']?:'Site officiel'],['token'=>Str::random(32),'destination_url'=>$d['external_url'],'is_active'=>true]);}
}
